apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-343f-8fjkj
  name: cluster-infra1-eu-central-1a
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-343f-8fjkj
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: cluster-infra1-eu-central-1a
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-343f-8fjkj
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-infra1-eu-central-1a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          infra: infra  
        creationTimestamp: null
      providerSpec:
        value:
          ami:
            id: ami-02fdd627029c0055b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-343f-8fjkj-worker-profile
          instanceType: m4.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: eu-central-1a
            region: eu-central-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-343f-8fjkj-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-343f-8fjkj-private-eu-central-1a
          tags:
          - name: kubernetes.io/cluster/cluster-343f-8fjkj
            value: owned
          userDataSecret:
            name: worker-user-data
